# Generated by Django 5.1.1 on 2024-09-06 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alojamientos', '0001_initial'),
        ('eventos', '0001_initial'),
        ('lugaresturisticos', '__first__'),
        ('restaurantes', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'RedSocial',
                'verbose_name_plural': 'RedesSociales',
                'db_table': 'gestiones.RedSocial',
            },
        ),
        migrations.CreateModel(
            name='ValoracionComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('texto', models.TextField()),
                ('valoracion', models.IntegerField()),
                ('interacciones', models.IntegerField()),
                ('alojamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alojamientos.alojamiento')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('lugar_turistico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugaresturisticos.lugarturistico')),
                ('red_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiones.redsocial')),
                ('restaurante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.restaurante')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ValoracionComentario',
                'verbose_name_plural': 'ValoracionesComentarios',
                'db_table': 'gestiones.ValoracionComentario',
            },
        ),
    ]
