# Generated by Django 5.1.1 on 2024-09-06 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoevento',
            name='precio',
        ),
        migrations.AddField(
            model_name='evento',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eventos.tipoevento'),
        ),
    ]
