# Generated by Django 5.1.1 on 2024-09-06 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='eventos.tipoevento'),
        ),
    ]
