# Generated by Django 5.1.1 on 2024-09-06 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_evento_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.tipoevento'),
        ),
        migrations.AlterField(
            model_name='tipoevento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
