# Generated by Django 5.1.1 on 2024-09-06 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_evento_nombre_alter_evento_tipo_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.tipoevento'),
        ),
    ]
