# Generated by Django 5.1.1 on 2024-09-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('imagen', models.ImageField(upload_to='media/imagenes/lugares-turisticos')),
                ('hora_apertura', models.DateField()),
                ('hora_cierre', models.DateField()),
            ],
            options={
                'verbose_name': 'LugarTuristico',
                'verbose_name_plural': 'LugaresTuristicos',
                'db_table': 'lugaresturisticos.LugarTuristico',
            },
        ),
    ]
