# Generated by Django 5.1.1 on 2024-09-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoalojamiento',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='tipohabitacion',
            name='precio',
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
