# Generated by Django 5.1.1 on 2024-09-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0002_remove_tipoalojamiento_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoalojamiento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
