# Generated by Django 5.1.1 on 2024-09-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0003_alter_alojamiento_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='hora_apertura',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='hora_cierre',
            field=models.TimeField(),
        ),
    ]
