# Generated by Django 5.1.1 on 2024-09-06 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_tipo_de_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.nacionalidad'),
        ),
    ]
