# Generated by Django 5.1.1 on 2024-09-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idioma',
            name='codigo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='nacionalidad',
            name='codigo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='nacionalidad',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
