# Generated by Django 5.1.1 on 2024-09-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_tipo_de_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
